### PR TITLE
Some documentation fixes (squashed)

### PR DESCRIPTION
**Pull request by bartgrantham**
Fixed smartquotes in code blocks in Quickstart.md
Added unzip to quickstart requirements to Quickstart.md
Fixed unmatched curly brace in Parameters annotation in ArchitectureOverview.md
Fixed a number of paths and clarified which .properties need editing in ConfigTheCTK.md
extra hyphen in 'cts-demo-java' in StructureAndRationale.md

### CODE REVIEW

**Comment by macieksmuga** [comment]
+1 thanks @bartgrantham - If I don't hear anything about this by Friday, I'm merging it in :)

**Comment by delagoya** [comment]
+1

**Comment by adamnovak** [comment]
+1, looks like mostly typo fixes and language improvements.

**Comment by bartgrantham** [comment]
Yup, minor stuff that I tripped over when working with it a couple weeks ago.

**Pull request merged**
