### PR TITLE
Biodata

### PR DESCRIPTION
**Pull request by david4096**
Scaffolding for tests for the biodata endpoints, specifically biosamples for now. Need tests for get by ID, searching readgroupsets, and callsets.

### CODE REVIEW

**Comment by macieksmuga** [comment]
Everything works, but the biodata in test_data is now contained in a directory structure, something we agreed upon at the beginning of this compliance project that we weren't going to do.

Let's discuss a consistent solution to this before going forward.

**Comment by macieksmuga** [comment]
+1 modulo flattening out the `biosample` and `individual` json files in test_data.

**Comment by david4096** [comment]
@macieksmuga The directory is flat again and the test files are named for their types. https://github.com/ga4gh/compliance/pull/179/commits/fb831810d2e6aba0f007f0c165dd7b74feb7554a#diff-140b3c2404155d50dab3b256bd9396d4R1

**Comment by macieksmuga** [comment]
+1

**Comment by david4096** [comment]
Closing in favor of https://github.com/ga4gh/compliance/pull/195

**Pull request closed without merging**
