### PR TITLE
Sequence annotation

### PR DESCRIPTION
**Pull request by macieksmuga**
Compliance tests on get and search endpoints for `FeatureSet` and `Feature` records.

### CODE REVIEW

**Comment by macieksmuga** [comment]
Corresponds to https://github.com/ga4gh/schemas/pull/591

**Comment by macieksmuga** [comment]
@sarahhunt @calbach Feel free to take a look in this one. Unless you have any objections, I'm planning on merging it in once https://github.com/ga4gh/schemas/pull/591 is accepted.

**Comment by macieksmuga** [comment]
ga4gh/schemas#591 was merged. Can I please get +1s for this associated PR? @diekhans @david4096  @saupchurch

**Comment by diekhans** [comment]
+1 please

**Comment by saupchurch** [comment]
+1

**Pull request merged**
