### PR TITLE
Updated reference set with JSON sidecar, adjusted variant metadata.

### PR DESCRIPTION
**Pull request by macieksmuga**
Consistency tweak and additional metadata to allow for running compliance data with the reference server.

### CODE REVIEW

**Comment by macieksmuga** [comment]
@jeromekelleher @dcolligan could you take a look at this? Based on my testing, this PR is what's needed to get the compliance data working with the reference server.

**Comment by hjellinek** [comment]
Note: this is related to the [Added shell script to wrangle compliance data into server format](https://github.com/ga4gh/server/pull/656) pull request.

**Comment by calbach** [comment]
Per #75, what about the `Reference` metadata?

**Comment by macieksmuga** [comment]
The main problem with the way this test-data directory is currently arranged is that it's not easy to expand to multiple datasets or reference sets. Thus, I was thinking of restructuring it into a more hierarchical directory format, possibly mirroring the reference server setup as follows:

```
- README_COMPLIANCE_DATA.md
- references/
  |- hg37.json
  |- hg37/
     |- ref_brca1.json
     |- ref_brca1.fa
- dataset1/
  |- <variant_set1>/
     |- <variants_file1>.vcf
     |- ...
  |- <variants_set2>/
     |...
  |- <reads_file1>.sam
  |...
- dataset2/
  |...
```

Another option would be to include an extra file (plaintext or json) that specifies what datafile goes with which reference or data-set.

**Comment by macieksmuga** [comment]
@calbach The `Reference` metadata is what's contained in the two .json files (one already in Master, the other introduced as part of this PR). But it's not enough, as it doesn't affiliate the data files with specific named reference or data sets.

**Comment by macieksmuga** [comment]
On second thought, it would make a lot more sense to just rename the files in `test-data` as follows:
```
brca1_<read_filename>.sam 
brca1_1kg-phase3_<variant_filename>.vcf
```
to make associations with datasets explicit, and assume that we're using a single reference set (named hg37 for the purposes of this dataset) for now.

this will be a) readable, b) trivial to implement and c) make it easy for me or others to write automatic data-bundlers for the various servers sourcing this data.

**Comment by jeromekelleher** [comment]
Looks good to me @macieksmuga. I think the hierarchical formatting is probably the easiest approach, as it makes it pretty clear which dataset reads and variants belong to, and what the names of the various objects are supposed to be.

**Comment by macieksmuga** [comment]
Thanks @jeromekelleher - I'm leaning towards the naming convention approach for now, as it'll be an incrementally smaller change. Going from that to a directory-hierarchical scheme (should we decide on going there) would also be relatively easy.

For context, I'm doing this now to fulfill @dcolligan's request for a python-based data prep script in https://github.com/ga4gh/server/pull/656 - and I realized that I should probably make it generic enough so that it didn't need to be adjusted every time I added another variant or read file (or dataset, for that matter).

**Comment by macieksmuga** [comment]
Could we work to merge this ASAP? - the compliance data were updated here to fix small internal inconsistencies, and to add in necessary "sidecar" metadata json files.

**Comment by jeromekelleher** [comment]
+1.

**Comment by macieksmuga** [comment]
I'm about to squish commits & merge this PR, as it fixes a critical bug with compliance data (without it, https://github.com/ga4gh/server/pull/656 - already merged - won't work properly).

**Pull request merged**
